name: Repo Sync

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Repo-Sync.yaml'

  schedule:
    - cron: 3-53/10 * * * *

jobs:
  jd-scripts:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: JDHelp
        run: |
          bash Scripts/Sync.sh \
            https://github.com/he1pu/JDHelp main \
            https://${{ github.repository_owner }}:${{ env.PAT}}@github.com/hyyds/jd-scripts

